###
GET http://localhost:5000/articles/

###
GET http://localhost:5000/articles/63e4f1697537335610829a8c

###
POST http://localhost:5000/articles/
Content-Type: application/json

{
    "message": "wkwkwkwkkw"
}

###
PUT http://localhost:5000/articles/63e4f1697537335610829a8c
Content-Type: application/json

{
    "message": "xixixi" 
}

# ###
# DELETE http://localhost:5000/articles/2
